[project]
name = "advent-of-code"
version = "0.1.0"
description = "Simple Advent of Code repository"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "adventofcode>=23.0b1",
    "pandas>=2.3.2",
]
